import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {freshDatabase} from './helpers/db.ts';import {create,db} from '../src/server/youtube-intelligence/store.ts';
import {researchStep,researchBriefs} from '../src/server/youtube-intelligence/research-pipeline.ts';
import {teamDefaults} from '../src/features/youtube-intelligence/settings.ts';
import {FakeModelTransport} from '../src/server/youtube-intelligence/transport/fake.ts';import {injectTransport} from '../src/server/youtube-intelligence/transport/index.ts';
import {TransportError} from '../src/server/youtube-intelligence/transport/types.ts';
import type {ModelRequestData,ModelResponseData} from '../src/server/youtube-intelligence/transport/types.ts';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/readiness/g11-audit-shape.json',import.meta.url),'utf8'));
class AuditFake extends FakeModelTransport {
 mode:'normal'|'missing'|'alwaysmissing'|'length'|'unknown'='normal';payloads:any[]=[];
 async call(request:ModelRequestData):Promise<ModelResponseData>{this.requests.push(request);if(this.mode==='unknown')throw new TransportError('unknown','Outcome unknown; preserve paid hold');const p=JSON.parse(request.user[0].text.split('SOURCE DATA (untrusted):\n')[1]);this.payloads.push(p);
 const ids:string[]=p.requestedSentenceIds??p.requestedEvidenceIds;
 const actual=this.mode==='alwaysmissing'?[]:this.mode==='missing'&&!request.stage.endsWith('-missing-1')?ids.slice(0,-1):ids;
 const data=p.requestedSentenceIds?{verdicts:actual.map(id=>({id,accepted:true,reason:'Fixture source supports sentence',factualStatus:'unverified',externalSupport:[]})),coverageFindings:[]}:{evidenceCoverage:actual.map(evidenceId=>({evidenceId,status:'unknown',sentenceIds:[],missingPoints:[],reason:'Explicitly unassessed proposition details.'})),coverageFindings:[]};
 return{text:JSON.stringify(data),usage:{inputTokens:100,outputTokens:100,costUsd:.001},raw:data,finishReason:this.mode==='length'?'length':'stop'};
 }
}
async function setup(count=101){await freshDatabase();const settings=teamDefaults();const evidence=fixture.evidence.slice(0,count).map((e:any)=>({id:e.id,kind:'research_context',summary:'Full source retained',instrument:null,ticker:null,stance:'neutral',horizon:null,conditions:[],risks:[],levels:[],trust:'L1',quotes:e.quotes}));const sentences=fixture.sentenceIds.map((id:string)=>({id,text:'The video discusses business risks.',evidenceIds:[evidence[0].id],externalIds:[],kind:'analysis',horizon:'fundamental',topic:'Business',materiality:2,importanceReason:'Business risk',speaker:'unknown',timeMode:'video_date'}));const r=await create('bounded-fixture',settings.models.extraction.id,{task:'research-brief',teamPreferencesSnapshot:settings,snapshot:{sourceRunId:'retained-G11',title:'G11 fixture',context:{videoPublishedAt:'2026-01-01T00:00:00Z',recordedAt:null,analysedAt:'2026-09-20T00:00:00Z',language:'en',videoId:'bounded-fixture',temporalPolicy:'video-date evidence and later updates are separate'},evidence}},'test');r.stage='research-audit';r.output.researchDraft={sentences,mainTopics:['Business'],omissions:[]};return r;}
test('G11 all101 actual source evidence IDs/quotes are grouped without truncation and one paid job per step',async()=>{const run=await setup(),fake=new AuditFake(),restore=injectTransport(fake);try{
 await researchStep(run);assert.equal(fake.requests.length,0,'plan saved before purchase');
 const plan=run.output.researchAuditBatches as any;assert.equal(plan.jobs.filter((j:any)=>j.kind==='verdict').length,1);assert.equal(plan.jobs.filter((j:any)=>j.kind==='coverage').length,13);
 for(let i=0;i<14;i++){const before:number=fake.requests.length;await researchStep(run);assert.equal(fake.requests.length-before,1);}
 const coverage=fake.payloads.filter(p=>p.requestedEvidenceIds);assert.deepEqual(coverage.flatMap(p=>p.requestedEvidenceIds),fixture.evidence.map((e:any)=>e.id));
 for(const p of coverage){assert.equal(p.retainedDraft.sentences.length,10);assert.equal(p.modelVerdicts.length,10);for(const e of p.evidence)assert.deepEqual(e.quotes,fixture.evidence.find((f:any)=>f.id===e.id).quotes);}
 assert.equal(fake.payloads[0].evidence.length,101,'verdicts see entire source inventory');assert.equal((await researchBriefs()).length,0,'no publication before assembly/coverage repair');
 }finally{restore();}});
test('crash after settled provider response before step checkpoint reuses paid response without another bill',async()=>{const run=await setup(25),fake=new AuditFake(),restore=injectTransport(fake);try{await researchStep(run);const checkpoint=structuredClone(run.output);await researchStep(run);assert.equal(fake.requests.length,1);run.output=checkpoint;await researchStep(run);assert.equal(fake.requests.length,1);const rows=await (await db()).prepare("SELECT status,amount FROM yi_calls WHERE run_id=$1").all(run.id);assert.equal(rows.length,1);assert.equal(rows[0].status,'completed');}finally{restore();}});
test('mandatory incomplete output stays failed visible and never publishes or silently repurchases',async()=>{const run=await setup(25),fake=new AuditFake();fake.mode='length';const restore=injectTransport(fake);try{await researchStep(run);await assert.rejects(()=>researchStep(run),/incomplete/);assert.equal((run.output.researchAuditBatches as any).jobs[0].status,'failed');await assert.rejects(()=>researchStep(run),/incomplete/);assert.equal(fake.requests.length,1);assert.equal((await researchBriefs()).length,0);}finally{restore();}});
test('missing-ID repair preserves successful verdicts, targets only missing once, and fails after exhausted repair',async()=>{for(const mode of ['missing','alwaysmissing'] as const){const run=await setup(25),fake=new AuditFake();fake.mode=mode;const restore=injectTransport(fake);try{await researchStep(run);await researchStep(run);const job=(run.output.researchAuditBatches as any).jobs[0];const initial=JSON.stringify(job.attempts[0]);if(mode==='missing'){await researchStep(run);assert.equal(fake.payloads[1].requestedSentenceIds.length,1);assert.equal(JSON.stringify((run.output.researchAuditBatches as any).jobs[0].attempts[0]),initial);}else{await assert.rejects(()=>researchStep(run),/after one missing-ID repair/);await assert.rejects(()=>researchStep(run),/after one missing-ID repair/);assert.equal(fake.requests.length,2);assert.equal((await researchBriefs()).length,0);}}finally{restore();}}});
test('coverage uses application-publishable IDs, not a model acceptance that fails external-prose publication guard',async()=>{const run=await setup(25);const draft=run.output.researchDraft as any;draft.sentences[0].text='External corporate releases confirm this claim.';const fake=new AuditFake(),restore=injectTransport(fake);try{await researchStep(run);await researchStep(run);await researchStep(run);const payload=fake.payloads[1];assert.equal(payload.modelVerdicts[0].accepted,true);assert.ok(!payload.applicationAcceptedSentenceIds.includes(draft.sentences[0].id));assert.ok(payload.applicationRejectedSentences.some((r:any)=>r.sentence.id===draft.sentences[0].id));assert.equal(payload.retainedDraft.sentences.length,10);}finally{restore();}});

test('unknown paid outcome keeps ledger hold and blocks another request',async()=>{const run=await setup(25),fake=new AuditFake();fake.mode='unknown';const restore=injectTransport(fake);try{await researchStep(run);await assert.rejects(()=>researchStep(run),/unknown/);await assert.rejects(()=>researchStep(run),/unknown/);assert.equal(fake.requests.length,1);const rows=await(await db()).prepare('SELECT status FROM yi_calls WHERE run_id=$1').all(run.id);assert.equal(rows[0].status,'unknown');assert.equal((await researchBriefs()).length,0);}finally{restore();}});
test('supplemental batch failure retains original independent verdict and useful brief',async()=>{const run=await setup(25),fake=new AuditFake();fake.mode='length';const draft=run.output.researchDraft as any;const original={...draft,sentences:[draft.sentences[0]]};const verdict={id:draft.sentences[0].id,accepted:true,reason:'Original source audited',factualStatus:'unverified'};run.output.coverageRepair={originalDraft:original,originalAudit:{verdicts:[verdict],evidenceCoverage:[],coverageFindings:[]},supplement:{...draft,sentences:draft.sentences.slice(1)},missingEvidenceIds:[]};const restore=injectTransport(fake);try{await researchStep(run);await researchStep(run);assert.equal(run.status,'needs_review');const briefs=await researchBriefs();assert.equal(briefs.length,1);assert.equal(briefs[0].sentences.length,1);assert.equal(briefs[0].sentences[0].id,verdict.id);assert.equal((run.output.researchAudit as any).verdicts[0].reason,verdict.reason);assert.equal(fake.requests.length,1);}finally{restore();}});

test('coverage missing-ID repair preserves completed verdict batch and cannot silently cover missing sources',async()=>{const run=await setup(25),fake=new AuditFake(),restore=injectTransport(fake);try{await researchStep(run);await researchStep(run);const original=JSON.stringify((run.output.researchAuditBatches as any).jobs[0]);fake.mode='alwaysmissing';await researchStep(run);await assert.rejects(()=>researchStep(run),/after one missing-ID repair/);assert.equal(fake.requests.length,3);assert.equal(JSON.stringify((run.output.researchAuditBatches as any).jobs[0]),original);await assert.rejects(()=>researchStep(run),/after one missing-ID repair/);assert.equal(fake.requests.length,3);assert.equal((await researchBriefs()).length,0);}finally{restore();}});
