import test from 'node:test';import assert from 'node:assert/strict';
import {cloudPlan} from '../deploy/cloud/plan.ts';
const fixture=()=>({project:'test-project',region:'us-central1',image:`us-central1-docker.pkg.dev/test-project/yti/app@sha256:${'a'.repeat(64)}`,webService:'yti-web',workerJob:'yti-worker',migrationJob:'yti-migrate',webServiceAccount:'yti-web@test-project.iam.gserviceaccount.com',workerServiceAccount:'yti-worker@test-project.iam.gserviceaccount.com',migrationServiceAccount:'yti-migrate@test-project.iam.gserviceaccount.com',cloudSqlInstance:'test-project:us-central1:yti',origin:'https://yti.example.com',budgetUsd:100,monthlyBudgetUsd:500,transcriptCredits:100,webSecrets:{DATABASE_URL:'yti-runtime-db:1',YTI_ACCESS_TOKEN:'yti-access:1'},workerSecrets:{DATABASE_URL:'yti-runtime-db:1'},migrationSecrets:{DATABASE_URL:'yti-migration-db:1',DATABASE_URL_UNPOOLED:'yti-migration-db:1'}});
test('cloud plan uses immutable image private web bounded worker and paused admission',()=>{const plan=cloudPlan(fixture());assert.equal(plan.length,3);assert.ok(plan.every(c=>c.args.includes('--project=test-project')));assert.ok(plan[0].args.includes('--no-allow-unauthenticated'));assert.ok(plan[1].args.includes('--max-retries=0'));assert.ok(plan[1].args.includes('--task-timeout=3600s'));assert.ok(plan[1].args.some(a=>a.includes('YTI_QUEUE_PAUSED=true')));assert.ok(plan[2].args.includes('--args=migrate'));});
test('cloud plan rejects mutable images secret values and unpinned secret versions',()=>{for(const mutate of [(c:any)=>c.image='example:latest',(c:any)=>c.workerSecrets.DATABASE_URL='postgres://user:password@host/db',(c:any)=>c.webSecrets.YTI_ACCESS_TOKEN='access:latest',(c:any)=>c.region='us-central1;echo injected']){const c=fixture();mutate(c);assert.throws(()=>cloudPlan(c));}});
import {spawnSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const start=fileURLToPath(new URL('../deploy/cloud/start.mjs',import.meta.url));
test('container refuses local database or missing hosted authentication without leaking invalid credentials',()=>{
 for(const env of [{DATABASE_URL:'not-a-url-secret-sentinel'},{DATABASE_URL:'postgresql://u:p@127.0.0.1/db'},{DATABASE_URL:'postgresql://u:p@127.0.0.2/db'},{DATABASE_URL:'postgresql://u:p@[::1]/db'},{DATABASE_URL:'postgresql://u:p@cloudsql/db',YTI_APP_ORIGIN:'https://example.com'}]){
  const result=spawnSync(process.execPath,[start,'web'],{env:{NODE_ENV:"test",PATH:process.env.PATH,...env},encoding:'utf8'});
  assert.notEqual(result.status,0);assert.ok(!result.stderr.includes('not-a-url-secret-sentinel'));
 }
});
test('build contexts exclude private local data credentials and user-owned component',()=>{
 for(const name of ['.dockerignore','.gcloudignore']){
  const rules=readFileSync(new URL(`../${name}`,import.meta.url),'utf8');assert.ok(rules.startsWith('**\n'));for(const excluded of ['**/.env*','**/data/**','**/ResearchBrief (1).tsx','**/.git/**'])assert.ok(rules.includes(excluded));assert.ok(!rules.includes('!deploy/cloud/**'),'private reviewed config JSON is not uploaded');
 }
 const docker=readFileSync(new URL('../Dockerfile',import.meta.url),'utf8');assert.match(docker,/FROM node:24-bookworm-slim/);assert.match(docker,/USER node/);assert.doesNotMatch(docker,/ARG .*KEY|COPY.*\.env/);
});
test('experiment uses dedicated DB references read-only input and durable result mounts while disabled',()=>{const c={...fixture(),webIapEnabled:true,experiment:{job:'yti-experiment',migrationJob:'yti-experiment-migrate',serviceAccount:'yti-experiment@test-project.iam.gserviceaccount.com',bundleBucket:'yti-frozen-input',resultsBucket:'yti-private-results',secrets:{DATABASE_URL:'yti-experiment-db:1',DATABASE_URL_UNPOOLED:'yti-experiment-db:1',GEMINI_API_KEY:'yti-gemini:1',OPENROUTER_API_KEY:'yti-critic:1'}}};const commands=cloudPlan(c);assert.equal(commands.length,5);assert.ok(commands[0].args.includes('--iap'));assert.ok(commands[3].args.includes('--args=experiment'));assert.ok(commands[3].args.some(a=>a.includes('bucket=yti-frozen-input,readonly=true')));assert.ok(commands[3].args.some(a=>a.includes('bucket=yti-private-results,readonly=false')));assert.ok(commands[3].args.some(a=>a.includes('YTI_CLOUD_EXPERIMENT_ENABLED=false')));assert.ok(commands[4].args.some(a=>a.includes('DATABASE_URL=yti-experiment-db:1')));assert.ok(!commands[4].args.some(a=>a.includes('GEMINI_API_KEY')));});
test('experiment entrypoint accepts Cloud SQL socket but refuses execution without explicit enablement',()=>{const r=spawnSync(process.execPath,[start,'experiment'],{env:{NODE_ENV:'test',DATABASE_URL:'postgresql://u:p@localhost/yti_experiment_test?host=%2Fcloudsql%2Ftest-project%3Aus-central1%3Ayti'},encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/requires explicit enablement/);assert.doesNotMatch(r.stderr,/cloud PostgreSQL endpoint/);});
