import test from 'node:test';import assert from 'node:assert/strict';
import {launchCloudWorker} from '../src/server/youtube-intelligence/cloud-worker-launcher.ts';
const config={enabled:true,paused:false,project:'test-project',region:'us-central1',job:'yti-worker'};
function deps(){const records:unknown[]=[];let claimed=false,posts=0;return {records,get posts(){return posts;},claim:async()=>{if(claimed)return false;claimed=true;return true;},record:async(r:unknown)=>{records.push(r);},request:async(url:string,init?:RequestInit)=>{if(url.includes('metadata.google.internal'))return Response.json({access_token:'fixture-access-token-long'});if(init?.method==='POST'){posts++;return Response.json({name:'projects/test-project/locations/us-central1/operations/test'});}return Response.json({executions:[]});}};}
test('concurrent enqueue wakes launch at most one job through shared lease',async()=>{const d=deps();const results=await Promise.all([launchCloudWorker(config,d),launchCloudWorker(config,d)]);assert.equal(d.posts,1);assert.deepEqual(results.map(r=>r.status).sort(),['debounced','launched']);});
test('existing unfinished execution suppresses another cloud launch',async()=>{const d=deps(),request=d.request;d.request=async(url,init)=>url.endsWith('executions?pageSize=100')?Response.json({executions:[{name:'active'}]}):request(url,init);assert.equal((await launchCloudWorker(config,d)).status,'running');assert.equal(d.posts,0);});
test('ambiguous launch outcome is retained and never automatically retried',async()=>{const d=deps(),request=d.request;d.request=async(url,init)=>{if(init?.method==='POST')throw Error('network interrupted');return request(url,init);};assert.equal((await launchCloudWorker(config,d)).status,'unknown');assert.equal((await launchCloudWorker(config,d)).status,'debounced');assert.ok(d.records.some((r:any)=>r.status==='unknown'));});
test('disabled paused and malformed listing cannot launch work',async()=>{for(const override of [{enabled:false},{paused:true}]){const d=deps();await launchCloudWorker({...config,...override},d);assert.equal(d.posts,0);}const d=deps(),request=d.request;d.request=async(url,init)=>url.includes('/executions?')?Response.json({executions:'bad'}):request(url,init);assert.equal((await launchCloudWorker(config,d)).status,'failed');assert.equal(d.posts,0);});
test('completed history beyond first page does not permanently suppress launches',async()=>{const d=deps(),request=d.request;let pages=0;d.request=async(url,init)=>{if(url.includes('/executions?')){pages++;return pages===1?Response.json({executions:[{completionTime:'2026-01-01T00:00:00Z'}],nextPageToken:'next'}):Response.json({executions:[{completionTime:'2026-01-01T00:00:00Z'}]});}return request(url,init);};assert.equal((await launchCloudWorker(config,d)).status,'launched');assert.equal(pages,2);assert.equal(d.posts,1);});
test('bounded incomplete inventory is failure, never falsely labelled as a running worker',async()=>{const d=deps(),request=d.request;let pages=0;d.request=async(url,init)=>{if(url.includes('/executions?')){pages++;return Response.json({executions:[],nextPageToken:String(pages)});}return request(url,init);};assert.equal((await launchCloudWorker(config,d)).status,'failed');assert.equal(pages,10);assert.equal(d.posts,0);});
