import test from 'node:test';import assert from 'node:assert/strict';
import {sourceNumericCheck} from '../src/features/youtube-intelligence/research-numeric-check.ts';
import {FinancialFact,validateBrief} from '../src/features/youtube-intelligence/research-brief.ts';
const fact=(quote:string,patch:Record<string,unknown>={})=>FinancialFact.parse({label:'Stated yield',value:3.5,currency:null,unit:'percent',unitDescription:'basis unspecified',relation:'exact',scale:'ones',period:null,basis:'not_stated',nature:'reported',evidenceId:'e',quote,...patch});
test('mixed Arabic and explicit English half rate is not assessed, not falsely mismatched or verified',()=>{const q='earning a daily yield of three and a half% and2.2% APY respectively.';const f=fact(q),before=JSON.stringify(f);const r=sourceNumericCheck(f,[q]);assert.equal(r.status,'not_assessed');assert.equal(JSON.stringify(f),before);});
test('recognized half amounts respect scale and preserve all values without decimal guessing',()=>{for(const [quote,value,scale]of [['three and a half million dollars',3.5,'millions'],['three-and-a-half billion dollars',3500,'millions'],['one and a half%',1.5,'ones']]as const){assert.equal(sourceNumericCheck(fact(quote,{value,scale,...(scale==='ones'?{}:{unit:'total',currency:'USD'})}),[quote]).status,'not_assessed');}const q='three and a half million dollars and2.2million';assert.equal(sourceNumericCheck(fact(q,{value:3.5,scale:'ones'}),[q]).status,'unresolved');});
test('nonmatching, unrelated and unsupported word phrases cannot excuse a different numerical claim',()=>{for(const [q,value]of [['three and a half% and2.2%',4.5],['three and a half years ago CPI was24',3.5],['lots of growth and CPI24',2.4],['twenty elephants and a half dozen; CPI24',2.4]]as const)assert.equal(sourceNumericCheck(fact(q,{value}),[q]).status,'unresolved');const years='three and a half million years ago; CPI24';assert.equal(sourceNumericCheck(fact(years,{value:3.5,scale:'millions',unit:'total',currency:'USD'}),[years]).status,'unresolved');const q='three and a half%';assert.equal(sourceNumericCheck(fact(q),[]).status,'unresolved');});
function publish(text:string){const q='earning a daily yield of three and a half% and2.2% APY respectively.';return validateBrief({sentences:[{id:'s',text,evidenceIds:['e'],externalIds:[],financialFacts:[fact(q),fact('2.2% APY',{value:2.2})],kind:'reported_fact',horizon:'fundamental',topic:'Account',materiality:2,importanceReason:'Product',speaker:'unknown',timeMode:'video_date'}],mainTopics:['Account'],omissions:[]},[{id:'e',kind:'research_context',summary:'Generated summary is not proof',instrument:null,ticker:null,stance:'neutral',horizon:null,conditions:[],risks:[],levels:[],trust:'L1',quotes:[{text:q,startId:'q',endId:'q',start:0,end:5,hash:null,translation:''}]}],[],{videoPublishedAt:'2026-01-01T00:00:00Z',recordedAt:null,analysedAt:'2026-09-20T00:00:00Z',language:'en',videoId:'v',channelId:null,temporalPolicy:'video-date evidence and later updates are separate'},[{id:'s',accepted:true,reason:'Audit accepts supplied source',factualStatus:'unverified'}]);}
test('neutral rate summary can remain unverified, but APY-as-daily-return still fails independent basis guard',()=>{const good=publish('Stated yields are3.5% and2.2% APY respectively; frequency remains unclear.');assert.equal(good.sentences.length,1);assert.equal(good.sentences[0].factualStatus,'unverified');const bad=publish('Daily yields are3.5% and2.2%.');assert.equal(bad.sentences.length,0);assert.match(bad.rejected[0].reasons.join(' '),/daily.*annual|annual.*daily/i);});
