import { test } from 'node:test';
import assert from 'node:assert/strict';
import { cloudDatabaseTarget, freshResearchSeed, alternatePairs, assertFrozenBundle, prepareFrozenBundle, admitFrozenResearch } from '../evaluations/targeted-audit/paired-runner.ts';
import { teamDefaults } from '../src/features/youtube-intelligence/settings.ts';
import { freshDatabase } from './helpers/db.ts';
const input={sourceRunId:'source',title:'A video',context:{videoId:'abcdefghijk',videoPublishedAt:'2026-09-01T00:00:00Z',recordedAt:null,analysedAt:'2026-09-19T00:00:00Z',language:'en',channelId:null,temporalPolicy:'video-date evidence and later updates are separate'},evidence:[],baseline:[],inventoryOmissions:[]};
function fixture(){
 return prepareFrozenBundle({id:'fixture',settings:teamDefaults(),implementationFiles:[{path:'package.json',sha256:'a'.repeat(64)}],cases:Array.from({length:20},(_,i)=>({case:i+1,videoId:`video${i}`,longVideo:i===10,source:{id:`source${i}`,model:'test',promptVersion:'v1',title:'Fixture',status:'completed',stage:'complete',createdAt:input.context.analysedAt,output:{source:{video_id:`video${i}`,language:'en',source_kind:'native_captions',segment_separator:' ',segments:[{id:'s0',text:'Test source',start_seconds:0,end_seconds:10}]},claims:[],keyPoints:[],mentions:[],metadata:{duration:10}}},snapshot:{...input,sourceRunId:`source${i}`,context:{...input.context,videoId:`video${i}`}},researchPlan:{queries:[],coverage:[]},retrievals:[],researchBaseline:[],provenance:{artifact:'fixture.json',sha256:'a'.repeat(64),researchRunId:`old${i}`}}))});
}
test('fresh paired seeds share frozen inputs and start after retained search without old draft/audit',()=>{const b=fixture();const a=freshResearchSeed(b,b.cases[0],'current'),t=freshResearchSeed(b,b.cases[0],'targeted');assert.equal(a.stage,'research-synthesis');assert.deepEqual(a.input.snapshot,t.input.snapshot);assert.deepEqual(a.output.retrievals,t.output.retrievals);assert.equal(a.output.researchDraft,undefined);assert.equal(t.output.researchAudit,undefined);assert.notEqual(a.id,t.id);assert.equal(a.input.reuseResearchCache,false);});
test('both arms are alternated and all20 remain in schedule',()=>{const p=alternatePairs(fixture());assert.equal(p.length,40);assert.deepEqual(p.slice(0,4).map(p=>p.arm),['current','targeted','targeted','current']);});
test('cloud target requires explicit dedicated benchmark database and refuses local/production',()=>{assert.throws(()=>cloudDatabaseTarget('postgres://a:b@localhost/yti_experiment_test'),/cloud/);assert.throws(()=>cloudDatabaseTarget('postgres://a:b@db.example/prod'),/dedicated/);assert.equal(cloudDatabaseTarget('postgres://a:b@db.example/yti_experiment_test').database,'yti_experiment_test');});
test('tampered frozen inputs cannot be admitted',()=>{const b=fixture();b.cases[0].snapshot.title='tampered';assert.throws(()=>assertFrozenBundle(b),/hash/);});
test('atomic admission reuses exact completed or interrupted rows without duplicate queued jobs',async()=>{const db=await freshDatabase();try{const b=fixture();const a=await admitFrozenResearch(db,b,b.cases[0],'current');const second=await admitFrozenResearch(db,b,b.cases[0],'current');assert.equal(a.id,second.id);const rows=await db.prepare('SELECT id FROM yi_runs').all();assert.equal(rows.length,2);assert.equal((await db.prepare('SELECT * FROM jobs').all()).length,0);await db.prepare("UPDATE yi_runs SET status='completed',stage='complete' WHERE id=$1").run(a.id);assert.equal((await admitFrozenResearch(db,b,b.cases[0],'current')).status,'completed');}finally{await db.close();}});
import { executeFrozenStep } from '../evaluations/targeted-audit/paired-runner.ts';
test('unsettled paid outcomes stop before executing or replacing a call',async()=>{const db=await freshDatabase();try{const b=fixture();const r=await admitFrozenResearch(db,b,b.cases[0],'current');await db.prepare('INSERT INTO yi_calls(id,run_id,stage,status,amount) VALUES($1,$2,$3,$4,$5)').run('uncertain',r.id,'synthesis-research','unknown',1);let invoked=0;await assert.rejects(executeFrozenStep(db,r,b,async()=>{invoked++;}),/Unsettled/);assert.equal(invoked,0);}finally{await db.close();}});
test('stage progress and timing checkpoint persist atomically and failures remain visible',async()=>{const db=await freshDatabase();try{const b=fixture();const r=await admitFrozenResearch(db,b,b.cases[0],'current');const out=await executeFrozenStep(db,r,b,async()=>{throw Error('fixture provider failure');});assert.equal(out.run.status,'failed');assert.ok(out.intent.executionSeconds!==null);const again=await admitFrozenResearch(db,b,b.cases[0],'current');assert.equal(again.status,'failed');assert.match(again.error!,/fixture/);}finally{await db.close();}});
import { prepareEvaluationArtifacts, readEvaluationArtifacts, exportEvaluationArtifacts } from '../evaluations/targeted-audit/paired-artifacts.ts';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
test('frozen evaluation plan exists before execution; later hash tampering is rejected',()=>{const root=mkdtempSync(join(tmpdir(),'yti-paired-artifacts-'));try{const folder=join(root,'evaluation'),b=fixture();prepareEvaluationArtifacts(b,{cases:b.cases.map(c=>({videoId:c.videoId}))},folder);assert.equal(readEvaluationArtifacts(b,folder).cases.length,20);writeFileSync(join(folder,'case-1-external.json'),'{}');assert.throws(()=>readEvaluationArtifacts(b,folder),/changed/);}finally{rmSync(root,{recursive:true,force:true});}});
test('export preserves unknown browser and quality evidence and reports precise frozen-retrieval scope',()=>{const root=mkdtempSync(join(tmpdir(),'yti-paired-export-'));try{const folder=join(root,'evaluation'),b=fixture(),e=prepareEvaluationArtifacts(b,{cases:b.cases.map(c=>({videoId:c.videoId}))},folder);const r=freshResearchSeed(b,b.cases[0],'current');r.status='completed';const raw={bundleSha256:b.sha256,evaluationPlanSha256:e.frozenPlan.sha256,runs:[r],calls:[],documents:[{kind:'pairedAdmission',id:r.id,payload:{runId:r.id,videoId:r.videoId,arm:'current',bundleSha256:b.sha256}},{kind:'pairedStep',id:'step',payload:{runId:r.id,stage:'research-synthesis',state:'finished',interruptedPrior:false,executionSeconds:2}}]};const result=exportEvaluationArtifacts(b,raw,folder,'session-1');assert.equal(result.runs[0].firstUsefulSeconds,null);assert.equal(result.runs[0].quality.criticalErrors.status,'unknown');assert.equal(result.runs[0].scope,'fresh-draft-audit-from-frozen-retrieval');assert.equal(result.admissions.length,1);}finally{rmSync(root,{recursive:true,force:true});}});
import { implementationManifest } from '../evaluations/targeted-audit/paired-runner.ts';
import { mkdirSync, symlinkSync } from 'node:fs';
test('cloud implementation identity excludes the user-owned UI copy and rejects code symlinks',()=>{const root=mkdtempSync(join(tmpdir(),'yti-paired-manifest-'));try{for(const dir of ['src/features/youtube-intelligence/ui','evaluations/targeted-audit','scripts'])mkdirSync(join(root,dir),{recursive:true});for(const file of ['package.json','package-lock.json','scripts/targeted-audit-paired.ts','scripts/targeted-audit-experiment.ts','src/real.ts'])writeFileSync(join(root,file),'fixture');const before=implementationManifest(root);writeFileSync(join(root,'src/features/youtube-intelligence/ui/ResearchBrief (1).tsx'),'user content never uploaded');assert.deepEqual(implementationManifest(root),before);symlinkSync(join(root,'src/real.ts'),join(root,'src/link.ts'));assert.throws(()=>implementationManifest(root),/Symlink/);}finally{rmSync(root,{recursive:true,force:true});}});
test('Cloud SQL sockets remain cloud-compatible without admitting arbitrary local sockets',()=>{assert.equal(cloudDatabaseTarget('postgresql://u:p@localhost/yti_experiment_trial?host=/cloudsql/project:us-central1:instance').database,'yti_experiment_trial');assert.throws(()=>cloudDatabaseTarget('postgresql://u:p@localhost/yti_experiment_trial?host=/tmp/socket'),/Cloud SQL/);});
test('export rejects mutated snapshots, wrong pipeline or admission video, and orphan costs',()=>{
 const root=mkdtempSync(join(tmpdir(),'yti-paired-identity-'));try{
 const b=fixture();for(const mutation of ['snapshot','pipeline','video','orphan']){
  const folder=join(root,mutation),e=prepareEvaluationArtifacts(b,{cases:b.cases.map(c=>({videoId:c.videoId}))},folder),r=freshResearchSeed(b,b.cases[0],'current');
  const admission={runId:r.id,videoId:r.videoId,arm:'current',bundleSha256:b.sha256};
  if(mutation==='snapshot')(r.input.snapshot as {title:string}).title='changed';if(mutation==='pipeline')r.input.researchPipeline='targeted-experimental';if(mutation==='video')admission.videoId='different';
  const raw={bundleSha256:b.sha256,evaluationPlanSha256:e.frozenPlan.sha256,runs:[r],calls:mutation==='orphan'?[{id:'unregistered',run_id:'other-run',stage:'synthesis',status:'completed',amount:1,metrics:{}}]:[],documents:[{kind:'pairedAdmission',id:r.id,payload:admission}]};
  assert.throws(()=>exportEvaluationArtifacts(b,raw,folder,'trial'),/identity|admission|Unregistered/);
 }
 }finally{rmSync(root,{recursive:true,force:true});}
});
