import test from 'node:test';
import assert from 'node:assert/strict';
import {planCoverageReuse} from '../src/server/youtube-intelligence/targeted-coverage-reuse.ts';
const sentence={id:'s1',evidenceIds:['e1'],text:'Original'};
const coverage={evidenceId:'e1',status:'covered',sentenceIds:['s1'],missingPoints:[],reason:'All material source details represented'};
function input(){return {evidence:[{id:'e1',quotes:['original']}],priorEvidence:[{id:'e1',quotes:['original']}],priorCoverage:[structuredClone(coverage)],priorAccepted:[structuredClone(sentence)],accepted:[structuredClone(sentence),{id:'s2',evidenceIds:['e2'],text:'New'}],priorContext:{cutoff:'date'},context:{cutoff:'date'},impact:{complete:true,sentenceIds:['s2'],affectedEvidenceIds:[] as string[]}};}
test('covered unchanged evidence reuses an explicit accepted dependency only after complete impact assessment',()=>{const result=planCoverageReuse(input());assert.deepEqual(result.reused,[coverage]);assert.deepEqual(result.reassessIds,[]);});
test('uncited relevance and indirect impact force reassessment',()=>{const i=input();i.impact.affectedEvidenceIds=['e1'];assert.deepEqual(planCoverageReuse(i).reassessIds,['e1']);});
test('unknown, missing or ambiguous impact never skips assessment',()=>{for(const impact of [null,{complete:false,sentenceIds:['s2'],affectedEvidenceIds:[]},{complete:true,sentenceIds:[],affectedEvidenceIds:[]},{complete:true,sentenceIds:['s2','s2'],affectedEvidenceIds:[]}]){assert.deepEqual(planCoverageReuse({...input(),impact}).reassessIds,['e1']);}});
test('partial missing unknown and invalid covered entries retain entire denominator',()=>{for(const status of ['partial','missing','unknown']){const i=input();i.priorCoverage[0].status=status;assert.deepEqual(planCoverageReuse(i).reassessIds,['e1']);}const i=input();i.priorCoverage[0].sentenceIds=[];assert.deepEqual(planCoverageReuse(i).reassessIds,['e1']);});
test('changed evidence context sentences and rejected dependencies invalidate reuse',()=>{const changes=[(i:any)=>i.evidence[0].quotes.push('qualification'),(i:any)=>i.context.cutoff='new',(i:any)=>i.accepted[0].text='Changed',(i:any)=>i.accepted.shift(),(i:any)=>i.priorCoverage.push({...coverage})];for(const change of changes){const i=input();change(i);assert.deepEqual(planCoverageReuse(i).reassessIds,['e1']);}});
test('absent prior inventory and malformed impact cannot authorize coverage',()=>{assert.deepEqual(planCoverageReuse({...input(),priorEvidence:[]}).reassessIds,['e1']);assert.deepEqual(planCoverageReuse({...input(),impact:{complete:true,sentenceIds:['s2'],affectedEvidenceIds:['foreign']}}).reassessIds,['e1']);});
test('direct new citation overrides an incorrectly empty model impact',()=>{const i=input();i.accepted[1].evidenceIds=['e1'];assert.deepEqual(planCoverageReuse(i).reassessIds,['e1']);});
test('duplicate evidence inventory IDs fail closed',()=>{const i=input();i.evidence.push(i.evidence[0]);assert.throws(()=>planCoverageReuse(i),/Duplicate/);});
