import test from 'node:test';
import assert from 'node:assert/strict';
import {advanceBoundedResearchAudit} from '../src/server/youtube-intelligence/bounded-research-audit.ts';
import {ResearchDraft,ResearchAudit,EvidenceRecord,AnalysisContext} from '../src/features/youtube-intelligence/research-brief.ts';
const evidence=['e1','e2'].map(id=>EvidenceRecord.parse({id,kind:'research_context',summary:'Business risk',instrument:null,ticker:null,stance:'neutral',horizon:null,conditions:[],risks:[],levels:[],trust:'L1',quotes:[{text:'The business faces material risks.',start:0,end:10,startId:'q1',endId:'q1',translation:'The business faces material risks.',hash:'fixture'}]}));
const context=AnalysisContext.parse({videoPublishedAt:'2026-01-01T00:00:00Z',recordedAt:null,analysedAt:'2026-09-20T00:00:00Z',language:'en',videoId:'test',temporalPolicy:'video-date evidence and later updates are separate'});
const sentence=(id:string,evidenceId:string)=>({id,text:'The business faces material risks.',evidenceIds:[evidenceId],externalIds:[],kind:'analysis',horizon:'fundamental',topic:'Business',materiality:2,importanceReason:'Business risk',speaker:'unknown',timeMode:'video_date'});
const original=ResearchDraft.parse({sentences:[sentence('s1','e1')],mainTopics:['Business'],omissions:[]});
const addition=ResearchDraft.parse({sentences:[sentence('s2','e2')],mainTopics:['Business'],omissions:[]});
const retained=ResearchDraft.parse({...original,sentences:[...original.sentences,...addition.sentences]});
const prior=ResearchAudit.parse({verdicts:[{id:'s1',accepted:true,reason:'Supported',factualStatus:'unverified',externalSupport:[]}],coverageFindings:['Keep original uncertainty'],evidenceCoverage:[{evidenceId:'e1',status:'covered',sentenceIds:['s1'],missingPoints:[],reason:'All details represented'},{evidenceId:'e2',status:'partial',sentenceIds:[],missingPoints:[{point:'Business risk',quote:'material risks'}],reason:'Missing risk'}]});
function input(targeted=true){return {draft:addition,retainedDraft:retained,evidence,previousAudit:prior,payload:{context,external:[],baseline:[],evidence},instructions:'Audit source',identity:{},...(targeted?{targeted:{previousBasis:{evidence,accepted:original.sentences,context:{context,external:[]}},context:{context,external:[]}}}:{})};}
function fake(impact:unknown={complete:true,sentenceIds:['s2'],affectedEvidenceIds:['e2']}){const calls:any[]=[];return {calls,invoke:async(stage:string,_instructions:string,p:any)=>{calls.push({stage,p});return p.requestedSentenceIds?{verdicts:p.requestedSentenceIds.map((id:string)=>({id,accepted:true,reason:'Supported',factualStatus:'unverified',externalSupport:[]})),coverageFindings:[],...(impact==null?{}:{coverageImpact:impact})}:{evidenceCoverage:p.requestedEvidenceIds.map((id:string)=>({evidenceId:id,status:'unknown',sentenceIds:[],missingPoints:[],reason:'Still uncertain'})),coverageFindings:[]};}};}
async function finish(output:Record<string,unknown>,data:ReturnType<typeof input>,f:ReturnType<typeof fake>){for(let n=0;n<12;n++){const r=await advanceBoundedResearchAudit(output,'supplement',data,f.invoke);if(r.done)return r;}throw Error('Never completed');}
test('experimental supplemental audit reuses only proven stable coverage and preserves unresolved denominator',async()=>{const output={},f=fake(),r=await finish(output,input(),f);assert.equal(f.calls.length,2);assert.deepEqual(f.calls[1].p.requestedEvidenceIds,['e2']);assert.equal(r.audit.evidenceCoverage.length,2);assert.equal(r.audit.evidenceCoverage.find(c=>c.evidenceId==='e2')?.status,'unknown');assert.deepEqual(r.audit.evidenceCoverage.find(c=>c.evidenceId==='e1'),prior.evidenceCoverage[0]);assert.ok(r.audit.coverageFindings.includes('Keep original uncertainty'));});
test('legacy path still audits all coverage and does not require impact output',async()=>{const f=fake(undefined),r=await finish({},input(false),f);assert.deepEqual(f.calls[1].p.requestedEvidenceIds,['e1','e2']);assert.equal(r.audit.evidenceCoverage.length,2);});
test('missing or foreign impact conservatively reviews every source item',async()=>{for(const impact of [null,{complete:false,sentenceIds:['s2'],affectedEvidenceIds:[]},{complete:true,sentenceIds:['s2'],affectedEvidenceIds:['foreign']}]){const f=fake(impact);await finish({},input(),f);assert.deepEqual(f.calls[1].p.requestedEvidenceIds,['e1','e2']);}});
test('checkpoint after verdict and reuse decision never repeats completed paid audit jobs',async()=>{let output:Record<string,unknown>={},f=fake();const data=input();await advanceBoundedResearchAudit(output,'supplement',data,f.invoke);await advanceBoundedResearchAudit(output,'supplement',data,f.invoke);assert.equal(f.calls.length,1);output=JSON.parse(JSON.stringify(output));await advanceBoundedResearchAudit(output,'supplement',data,f.invoke);assert.equal(f.calls.length,1);output=JSON.parse(JSON.stringify(output));await finish(output,data,f);assert.equal(f.calls.length,2);await finish(output,data,f);assert.equal(f.calls.length,2);});
test('changed experiment context blocks checkpoint reuse before any further paid request',async()=>{const output={},f=fake();const data=input();await advanceBoundedResearchAudit(output,'supplement',data,f.invoke);data.targeted!.context.external.push('changed' as never);await assert.rejects(()=>advanceBoundedResearchAudit(output,'supplement',data,f.invoke),/input changed/);assert.equal(f.calls.length,0);});
test('nine-item paired fixture reduces supplement invokes from three to two with all nine assessments retained',async()=>{
 const inventory=Array.from({length:9},(_,n)=>({...evidence[0],id:`e${n+1}`}));
 const oldDraft=ResearchDraft.parse({...original,sentences:[{...original.sentences[0],evidenceIds:inventory.slice(0,8).map(e=>e.id)}]});
 const newDraft=ResearchDraft.parse({...addition,sentences:[{...addition.sentences[0],evidenceIds:['e9']}]});
 const oldAudit=ResearchAudit.parse({...prior,evidenceCoverage:inventory.map((e,n)=>({evidenceId:e.id,status:n<8?'covered':'partial',sentenceIds:n<8?['s1']:[],missingPoints:n<8?[]:[{point:'Business risk',quote:'material risks'}],reason:'Source assessment'}))});
 const arms=[];
 for(const experimental of [false,true]){
  const data=input(experimental);data.evidence=inventory;data.draft=newDraft;data.retainedDraft={...oldDraft,sentences:[...oldDraft.sentences,...newDraft.sentences]};data.previousAudit=oldAudit;data.payload.evidence=inventory;
  if(data.targeted){data.targeted.previousBasis={...data.targeted.previousBasis,evidence:inventory,accepted:oldDraft.sentences};}
  const f=fake({complete:true,sentenceIds:['s2'],affectedEvidenceIds:['e9']});const result=await finish({},data,f);
  assert.equal(result.audit.evidenceCoverage.length,9);assert.equal(new Set(result.audit.evidenceCoverage.map(e=>e.evidenceId)).size,9);arms.push(f.calls.length);
 }
 assert.deepEqual(arms,[3,2]);
});
test('malformed impact response fails visibly and never authorizes silent coverage reuse',async()=>{const output:Record<string,unknown>={},f=fake({complete:'yes',sentenceIds:['s2'],affectedEvidenceIds:[]});await advanceBoundedResearchAudit(output,'supplement',input(),f.invoke);await assert.rejects(()=>advanceBoundedResearchAudit(output,'supplement',input(),f.invoke));await assert.rejects(()=>advanceBoundedResearchAudit(output,'supplement',input(),f.invoke));assert.equal(f.calls.length,1);assert.equal((output.supplement as any).reuse,undefined);});
