import { z } from "zod";
import { Source } from "../../features/youtube-intelligence/contracts.ts";

// Native SRT is retained cue-by-cue. Text, line breaks and punctuation are not polished.
export function normalizeTapline(
  input: unknown,
  videoId: string,
  language: string,
) {
  const data = z
    .object({
      transcript: z.string().min(1),
      is_auto_generated: z.boolean(),
      metadata: z.object({
        video_id: z.literal(videoId),
        duration: z.number().positive(),
      }),
    })
    .parse(input);
  const clock = (value: string) => {
    const m = /^(\d{2,}):([0-5]\d):([0-5]\d),(\d{3})$/.exec(value);
    if (!m) throw Error("Invalid SRT timestamp");
    return (
      Number(m[1]) * 3600 +
      Number(m[2]) * 60 +
      Number(m[3]) +
      Number(m[4]) / 1000
    );
  };
  const cues = data.transcript
    .replace(/\r\n/g, "\n")
    .trim()
    .split(/\n\s*\n/);
  const source = Source.parse({
    video_id: videoId,
    language,
    source_kind: "native_captions_tapline",
    segment_separator: /^(zh|yue|ja)/.test(language) ? "" : " ",
    segments: cues.map((cue, i) => {
      const lines = cue.split("\n");
      if (!/^\d+$/.test(lines[0])) throw Error("Invalid SRT cue number");
      const range = /^(\S+) --> (\S+)$/.exec(lines[1]);
      if (!range) throw Error("Invalid SRT cue range");
      return {
        id: `s${String(i + 1).padStart(5, "0")}`,
        text: lines.slice(2).join("\n"),
        start_seconds: clock(range[1]),
        end_seconds: clock(range[2]),
      };
    }),
  });
  if (source.segments.some((s) => s.end_seconds! > data.metadata.duration + 5))
    throw Error("Transcript extends beyond video duration");
  return {
    source,
    durationSeconds: data.metadata.duration,
    autoGenerated: data.is_auto_generated,
  };
}

// BibiGPT's subtitle endpoint may use captions or ASR; do not assert a native origin.
// The polished-text endpoint is intentionally not supported as verbatim evidence.
export function normalizeBibiGPT(input: unknown, videoId: string) {
  const data = z
    .object({
      success: z.literal(true),
      id: z.literal(videoId),
      service: z.literal("youtube"),
      detail: z.object({
        id: z.literal(videoId),
        duration: z.number().positive(),
        rawLang: z.string(),
        isPreviewOnly: z.boolean().optional(),
        subtitlesArray: z
          .array(
            z.object({
              startTime: z.number().nonnegative(),
              end: z.number().nonnegative(),
              text: z.string().min(1),
            }),
          )
          .min(1),
      }),
    })
    .parse(input);
  if (data.detail.isPreviewOnly)
    throw Error("Preview subtitles are not a complete source");
  const source = Source.parse({
    video_id: videoId,
    // Live API can return an empty language even with valid subtitles.
    // Preserve that uncertainty instead of asserting the requested language.
    language: data.detail.rawLang || undefined,
    source_kind: "provider_transcript_bibigpt",
    segment_separator: /^(zh|yue|ja)/.test(data.detail.rawLang) ? "" : " ",
    segments: data.detail.subtitlesArray.map((s, i) => ({
      id: `s${String(i + 1).padStart(5, "0")}`,
      text: s.text,
      start_seconds: s.startTime,
      end_seconds: s.end,
    })),
  });
  if (source.segments.some((s) => s.end_seconds! > data.detail.duration + 5))
    throw Error("Transcript extends beyond video duration");
  return { source, durationSeconds: data.detail.duration };
}
