-- Databases that predated the migration runner had version 1 stamped rather
-- run, so columns the baseline added later may be missing. Every statement is
-- idempotent; on an up-to-date database this changes nothing.
-- Order matters: tables, then columns, then the indexes that need them.
CREATE TABLE IF NOT EXISTS yi_runs(id TEXT PRIMARY KEY,video_id TEXT,url TEXT,model TEXT,prompt_version TEXT,title TEXT,status TEXT,stage TEXT,created_at TEXT,updated_at TEXT,error TEXT,input TEXT,output TEXT,cost DOUBLE PRECISION DEFAULT 0,lease_until BIGINT DEFAULT 0,lease_token TEXT);
CREATE TABLE IF NOT EXISTS yi_calls(id TEXT PRIMARY KEY,run_id TEXT,stage TEXT,status TEXT,amount DOUBLE PRECISION,metrics TEXT,attempt INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS yi_responses(id TEXT PRIMARY KEY,run_id TEXT,stage TEXT,payload TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS yi_heartbeat(id INTEGER PRIMARY KEY,at BIGINT);
CREATE TABLE IF NOT EXISTS yi_documents(kind TEXT,id TEXT,payload TEXT,created_at TEXT,updated_at TEXT,PRIMARY KEY(kind,id));
CREATE TABLE IF NOT EXISTS yi_events(id TEXT PRIMARY KEY,kind TEXT,entity_id TEXT,at TEXT,payload TEXT);
CREATE TABLE IF NOT EXISTS yi_prompts(id TEXT PRIMARY KEY,hash TEXT UNIQUE,payload TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS yi_discoveries(video_id TEXT PRIMARY KEY,channel_id TEXT,payload TEXT,discovered_at TEXT,run_id TEXT);
CREATE TABLE IF NOT EXISTS yi_shares(token_hash TEXT PRIMARY KEY,id TEXT UNIQUE,snapshot TEXT,created_at TEXT,expires_at TEXT,revoked_at TEXT);
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS attempt INTEGER DEFAULT 1;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS video_id TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS prompt_version TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS stage TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS error TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS input TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS output TEXT;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS cost DOUBLE PRECISION DEFAULT 0;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS lease_until BIGINT DEFAULT 0;
ALTER TABLE yi_runs ADD COLUMN IF NOT EXISTS lease_token TEXT;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS run_id TEXT;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS stage TEXT;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS amount DOUBLE PRECISION;
ALTER TABLE yi_calls ADD COLUMN IF NOT EXISTS metrics TEXT;
ALTER TABLE yi_responses ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_responses ADD COLUMN IF NOT EXISTS run_id TEXT;
ALTER TABLE yi_responses ADD COLUMN IF NOT EXISTS stage TEXT;
ALTER TABLE yi_responses ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE yi_responses ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE yi_heartbeat ADD COLUMN IF NOT EXISTS id INTEGER;
ALTER TABLE yi_heartbeat ADD COLUMN IF NOT EXISTS at BIGINT;
ALTER TABLE yi_documents ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE yi_documents ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_documents ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE yi_documents ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE yi_documents ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE yi_events ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_events ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE yi_events ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE yi_events ADD COLUMN IF NOT EXISTS at TEXT;
ALTER TABLE yi_events ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE yi_prompts ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_prompts ADD COLUMN IF NOT EXISTS hash TEXT;
ALTER TABLE yi_prompts ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE yi_prompts ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE yi_discoveries ADD COLUMN IF NOT EXISTS video_id TEXT;
ALTER TABLE yi_discoveries ADD COLUMN IF NOT EXISTS channel_id TEXT;
ALTER TABLE yi_discoveries ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE yi_discoveries ADD COLUMN IF NOT EXISTS discovered_at TEXT;
ALTER TABLE yi_discoveries ADD COLUMN IF NOT EXISTS run_id TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS token_hash TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS id TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS snapshot TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS expires_at TEXT;
ALTER TABLE yi_shares ADD COLUMN IF NOT EXISTS revoked_at TEXT;
CREATE INDEX IF NOT EXISTS yi_runs_queue ON yi_runs(status,lease_until,created_at);
CREATE INDEX IF NOT EXISTS yi_calls_run_stage ON yi_calls(run_id,stage);
CREATE INDEX IF NOT EXISTS yi_documents_kind ON yi_documents(kind,created_at);
CREATE INDEX IF NOT EXISTS yi_discoveries_channel ON yi_discoveries(channel_id,discovered_at);
CREATE INDEX IF NOT EXISTS yi_calls_run_stage_attempt ON yi_calls(run_id,stage,attempt);
